### ISSUE TITLE
On Windows, how can I build the .a library file? I can only make .lib and .dll through VS.

### ISSUE THREAD

**Issue by erfg12** [pdpdds/allegro4_dos#1]
```
C:\Users\newgm>cd C:\Users\newgm\Documents\GitHub\allegro4_dos\msvc15\lib\djgpp

C:\Users\newgm\Documents\GitHub\allegro4_dos\msvc15\lib\djgpp>setenv

C:\Users\newgm\Documents\GitHub\allegro4_dos\msvc15\lib\djgpp>cd C:\Users\newgm\Documents\GitHub\allegro4_dos\sample\1_helloworld

C:\Users\newgm\Documents\GitHub\allegro4_dos\sample\1_helloworld>make
BUILD... main.exe
gcc -I. -I..\\..\\msvc15\\include -L..\..\msvc15\build\Debug main.c -o main.exe -lallegro
C:/Users/newgm/Documents/GitHub/allegro4_dos/msvc15/lib/djgpp/lib/gcc/i586-pc-msdosdjgpp/10.2.0/../../../../i586-pc-msdosdjgpp/bin/ld.exe: cannot find -lallegro
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:13: all] Error 1
```

```
C:\Users\newgm\Documents\GitHub\allegro4_dos\msvc15\build\Debug>dir
 Volume in drive C has no label.
 Volume Serial Number is BE43-44BF

 Directory of C:\Users\newgm\Documents\GitHub\allegro4_dos\msvc15\build\Debug

04/27/2022  09:19 PM    <DIR>          .
04/27/2022  08:28 PM    <DIR>          ..
04/27/2022  08:31 PM         1,180,672 allegro.dll
04/27/2022  08:31 PM           178,791 allegro.exp
04/27/2022  08:31 PM           740,352 allegro.idb
04/27/2022  08:31 PM         2,647,152 allegro.ilk
04/27/2022  08:31 PM         4,700,390 allegro.lib
04/27/2022  08:31 PM           707,468 allegro.map
04/27/2022  08:31 PM         3,411,968 allegro.pdb
               7 File(s)     13,566,793 bytes
               2 Dir(s)  262,259,134,464 bytes free
```

**Comment by pdpdds** [comment]
go to /msvc15/build folder and open dos_dev.sln and build it.
then you can generate allegro.lib.

to build dos program, download djgpp.rar in release tab.
extract it and execute djgpp.bat. you will see cmd shell.
move to source code folder, for example 1_helloworld folder.
then enter make.

**Comment by pdpdds** [comment]
![화면 캡처 2022-04-28 134417](https://user-images.githubusercontent.com/1445129/165678279-9b9753a5-5b9d-4a0f-9e72-fce3e10c828e.png)

**Comment by erfg12** [comment]
```
C:\Users\newgm\Documents\GitHub\DOS_SharkShark>mingw32-make
BUILD... main.exe
gcc -I. -Ivendor/allegro-4.2.2-xc/include -Lvendor/allegro-4.2.2-xc/lib src/main.c -o main.exe -lalleg
C:/Users/newgm/Documents/GitHub/DOS_SharkShark/vendor/djgpp/lib/gcc/i586-pc-msdosdjgpp/10.2.0/../../../../i586-pc-msdosdjgpp/bin/ld.exe: cannot find -lalleg
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [Makefile:13: all] Error 1
```

Here's my modified Makefile:
```
CFLAGS = -I. -Ivendor/allegro-4.2.2-xc/include
LDFLAGS = -Lvendor/allegro-4.2.2-xc/lib

# -------- 실행 프로그램 이름 입력 --------
PROGRAM = main

# -------- 컴파일시킬 소스 파일들 --------
SRC = src/$(PROGRAM).c

# -------- 기본적인 컴파일 --------
all: src/$(PROGRAM).c
@echo BUILD... $(PROGRAM).exe 
gcc $(CFLAGS) $(LDFLAGS) $(SRC) -o $(PROGRAM).exe -lalleg
```

**Comment by pdpdds** [comment]
https://github.com/pdpdds/allegro4_dos/releases

download djgpp.rar

**Comment by erfg12** [comment]
That worked. Do you know if this setup will work when compiling for Linux or Mac?

**Comment by pdpdds** [comment]
what do you want exactly?

1. to generate win32 binary in linux.
2. to generate dos binary in linux
3. to geneate elf binary in linux

**Comment by erfg12** [comment]
Sorry I should have been more clear. I'm making a game for DOS in Allegro. I have a Windows desktop PC, but I also have a Mac air laptop. I want to be able to compile the DOS program on both systems.

**Comment by pdpdds** [comment]
check this. i tested in wsl2(ubuntu 20.04 lts)

https://github.com/andrewwutw/build-djgpp
you need not to build djgpp. use pre-compiled binary. djgpp-linux64-gcc1020.tar.bz2

set DJGPP_GCC variable. for example, in my pc

 export DJGPP_GCC=/mnt/c/temp/allegro4_dos/djgpp/bin/i586-pc-msdosdjgpp-gcc

https://github.com/msikma/allegro-4.2.2-xc



retro@TABLET-U0S17BEP:/mnt/c/temp/allegro4_dos/sample/1_helloworld$
retro@TABLET-U0S17BEP:/mnt/c/temp/allegro4_dos/sample/1_helloworld$ make
BUILD... main.exe
/mnt/c/temp/allegro4_dos/djgpp/bin/i586-pc-msdosdjgpp-gcc -I../../include -I../../allegro/include -L../../allegro/lib/djgpp main.c -o main.exe -lalleg
retro@TABLET-U0S17BEP:/mnt/c/temp/allegro4_dos/sample/1_helloworld$


CFLAGS = -I../../include -I../../allegro/include
LDFLAGS = -L../../allegro/lib/djgpp

PROGRAM = main
CC=$(DJGPP_GCC)
SRC = $(PROGRAM).c

all: $(PROGRAM).c
	@echo BUILD... $(PROGRAM).exe 
	$(CC) $(CFLAGS) $(LDFLAGS) $(SRC) -o $(PROGRAM).exe -lalleg

**Comment by pdpdds** [comment]
now i updated djgpp.rar. now you can test build helloworld project in linux.
execute below command.

. setenv

then build it.

**Comment by erfg12** [comment]
```
jakefliss@Jake-laptop allegro4_dos-master % chmod a+x ./setenv
jakefliss@Jake-laptop allegro4_dos-master % ./setenv
jakefliss@Jake-laptop allegro4_dos-master % cd ./sample/1_helloworld
jakefliss@Jake-laptop 1_helloworld % make
BUILD... main.exe
I. -I../../allegro/include -L../../allegro/lib main.c -o main.exe -lalleg
make: I.: No such file or directory
make: [all] Error 1 (ignored)
```

**Comment by pdpdds** [comment]
not ./setenv

. setenv

**Comment by pdpdds** [comment]
![retro](https://user-images.githubusercontent.com/1445129/166345204-374758bd-695f-41e6-a918-b3ae063ba450.png)
